#!/bin/bash

PALCONFIGDIR=/home/palserver/Pal/Saved/Config/LinuxServer
PALCONFIG=$PALCONFIGDIR/PalWorldSettings.ini

# ensure config dir is created
mkdir -p $PALCONFIGDIR

# copy template
cp /home/palserver/PalWorldSettings.ini $PALCONFIG

# copy in new settings using sed
sed -i "s/%DIFFICULTY%/$DIFFICULTY/g" $PALCONFIG
sed -i "s/%DAYTIMESPEEDRATE%/$DAYTIMESPEEDRATE/g" $PALCONFIG 
sed -i "s/%NIGHTTIMESPEEDRATE%/$NIGHTTIMESPEEDRATE/g" $PALCONFIG 
sed -i "s/%EXPRATE%/$EXPRATE/g" $PALCONFIG
sed -i "s/%PALCAPTURERATE%/$PALCAPTURERATE/g" $PALCONFIG 
sed -i "s/%PALSPAWNNUMRATE%/$PALSPAWNNUMRATE/g" $PALCONFIG 
sed -i "s/%PALDAMAGERATEATTACK%/$PALDAMAGERATEATTACK/g" $PALCONFIG 
sed -i "s/%PALDAMAGERATEDEFENSE%/$PALDAMAGERATEDEFENSE/g" $PALCONFIG 
sed -i "s/%PLAYERDAMAGERATEATTACK%/$PLAYERDAMAGERATEATTACK/g" $PALCONFIG 
sed -i "s/%PLAYERDAMAGERATEDEFENSE%/$PLAYERDAMAGERATEDEFENSE/g" $PALCONFIG 
sed -i "s/%PLAYERSTOMACHDECREASERATE%/$PLAYERSTOMACHDECREASERATE/g" $PALCONFIG 
sed -i "s/%PLAYERSTAMINADECREASERATE%/$PLAYERSTAMINADECREASERATE/g" $PALCONFIG 
sed -i "s/%PLAYERAUTOHPREGENERATE%/$PLAYERAUTOHPREGENERATE/g" $PALCONFIG 
sed -i "s/%PLAYERAUTOHPREGENEINSLEEP%/$PLAYERAUTOHPREGENEINSLEEP/g" $PALCONFIG
sed -i "s/%PALSTOMACHDECREASERATE%/$PALSTOMACHDECREASERATE/g" $PALCONFIG 
sed -i "s/%PALSTAMINADECREASERATE%/$PALSTAMINADECREASERATE/g" $PALCONFIG 
sed -i "s/%PALAUTOHPREGENERATE%/$PALAUTOHPREGENERATE/g" $PALCONFIG
sed -i "s/%PALAUTOHPREGENEINSLEEP%/$PALAUTOHPREGENEINSLEEP/g" $PALCONFIG 
sed -i "s/%BUILDOBJECTDAMAGERATE%/$BUILDOBJECTDAMAGERATE/g" $PALCONFIG 
sed -i "s/%BUILDOBJECTDETERIORATIONDAMAGERATE%/$BUILDOBJECTDETERIORATIONDAMAGERATE/g" $PALCONFIG 
sed -i "s/%COLLECTIONDROPRATE%/$COLLECTIONDROPRATE/g" $PALCONFIG 
sed -i "s/%COLLECTIONOBJECTHPRATE%/$COLLECTIONOBJECTHPRATE/g" $PALCONFIG
sed -i "s/%COLLECTIONOBJECTRESPAWNSPEEDRATE%/$COLLECTIONOBJECTRESPAWNSPEEDRATE/g" $PALCONFIG 
sed -i "s/%ENEMYDROPITEMRATE%/$ENEMYDROPITEMRATE/g" $PALCONFIG
sed -i "s/%DEATHPENALTY%/$DEATHPENALTY/g" $PALCONFIG 
sed -i "s/%ENABLE_PVP_DAMAGE%/$ENABLE_PVP_DAMAGE/g" $PALCONFIG
sed -i "s/%ENABLE_FF%/$ENABLE_FF/g" $PALCONFIG 
sed -i "s/%ENABLE_RAIDS%/$ENABLE_RAIDS/g" $PALCONFIG 
sed -i "s/%ACTIVE_UNKO%/$ACTIVE_UNKO/g" $PALCONFIG 
sed -i "s/%ENABLE_AIMASSIST_PAD%/$ENABLE_AIMASSIST_PAD/g" $PALCONFIG 
sed -i "s/%ENABLE_AIMASSIST_KEY%/$ENABLE_AIMASSIST_KEY/g" $PALCONFIG 
sed -i "s/%DROPITEM_MAXNUM%/$DROPITEM_MAXNUM/g" $PALCONFIG 
sed -i "s/%DROPITEM_MAXNUM_UNKO%/$DROPITEM_MAXNUM_UNKO/g" $PALCONFIG 
sed -i "s/%DROPITEM_ALIVEMAXHOURS%/$DROPITEM_ALIVEMAXHOURS/g" $PALCONFIG 
sed -i "s/%BASECAMP_MAXNUM%/$BASECAMP_MAXNUM/g" $PALCONFIG
sed -i "s/%BASECAMP_WORKERMAXNUM%/$BASECAMP_WORKERMAXNUM/g" $PALCONFIG
sed -i "s/%AUTORESETGUILD_NOONLINEPLAYERS%/$AUTORESETGUILD_NOONLINEPLAYERS/g" $PALCONFIG 
sed -i "s/%AUTORESETGUILD_TIMENOONLINEPLAYERS%/$AUTORESETGUILD_TIMENOONLINEPLAYERS/g" $PALCONFIG 
sed -i "s/%GUILD_PLAYERMAXNUM%/$GUILD_PLAYERMAXNUM/g" $PALCONFIG 
sed -i "s/%PALEGGDEFAULTHATCHINGTIME%/$PALEGGDEFAULTHATCHINGTIME/g" $PALCONFIG 
sed -i "s/%WORK_SPEEDRATE%/$WORK_SPEEDRATE/g" $PALCONFIG 
sed -i "s/%IS_MULTIPLAY%/$IS_MULTIPLAY/g" $PALCONFIG 
sed -i "s/%IS_PVP%/$IS_PVP/g" $PALCONFIG
sed -i "s/%CANPICKUPOTHERGUILDDROP%/$CANPICKUPOTHERGUILDDROP/g" $PALCONFIG 
sed -i "s/%ENABLE_NONLOGINPENALTY%/$ENABLE_NONLOGINPENALTY/g" $PALCONFIG
sed -i "s/%ENABLE_FASTTRAVEL%/$ENABLE_FASTTRAVEL/g" $PALCONFIG 
sed -i "s/%ENABLE_STARTSELECTION%/$ENABLE_STARTSELECTION/g" $PALCONFIG 
sed -i "s/%EXIST_AFTER_LOGOUT%/$EXIST_AFTER_LOGOUT/g" $PALCONFIG 
sed -i "s/%ENABLE_DEFENSE_OTHER_GUILD_PLAYER%/$ENABLE_DEFENSE_OTHER_GUILD_PLAYER/g" $PALCONFIG 
sed -i "s/%COOP_PLAYER_MAX_NUM%/$COOP_PLAYER_MAX_NUM/g" $PALCONFIG 
sed -i "s/%SERVER_PLAYER_MAX_NUM%/$SERVER_PLAYER_MAX_NUM/g" $PALCONFIG
sed -i "s/%SERVER_NAME%/$SERVER_NAME/g" $PALCONFIG 
sed -i "s/%SERVER_DESCRIPTION%/$SERVER_DESCRIPTION/g" $PALCONFIG 
sed -i "s/%ADMIN_PASSWORD%/$ADMIN_PASSWORD/g" $PALCONFIG 
sed -i "s/%SERVER_PASSWORD%/$SERVER_PASSWORD/g" $PALCONFIG 
sed -i "s/%PUBLIC_PORT%/$PUBLIC_PORT/g" $PALCONFIG 
sed -i "s/%PUBLIC_IP%/$PUBLIC_IP/g" $PALCONFIG 
sed -i "s/%RCON_ENABLED%/$RCON_ENABLED/g" $PALCONFIG 
sed -i "s/%RCON_PORT%/$RCON_PORT/g" $PALCONFIG 
sed -i "s/%REGION%/$REGION/g" $PALCONFIG 
sed -i "s/%USE_AUTH%/$USE_AUTH/g" $PALCONFIG 
sed -i "s*%BANLIST_URL%*$BANLIST_URL*g" $PALCONFIG 

# set permissions
chown -R palserver /home/palserver

# start server
sudo -u palserver ./PalServer.sh
